#!/usr/bin/env python3
""" Script that automatically installs protonfixes in all Proton installations
"""

import glob
import os
import re
import shutil


STEAM_DIRS = ["~/.local/share/Steam", "~/.steam/steam"]
LIBRARY_RE = re.compile(r'"\d*"\s*"(?P<path>(\/\w*)*)"')
LF_PATH = 'steamapps/libraryfolders.vdf'
PROTON_PATH = 'steamapps/common/Proton'


def find_steam_installation():
    """ Finds the steam user installation folder by looking in STEAM_DIRS
    """
    for path in STEAM_DIRS:
        dirpath = os.path.expanduser(path)
        if os.path.isdir(dirpath):
            return dirpath
    raise NotADirectoryError("Steam directory not found")


def find_libraries(steam_dir):
    """ Finds additional library folders with the LIBRARY_RE regex
    """
    lf_path = os.path.join(steam_dir, LF_PATH)
    library_dirs = []
    with open(lf_path) as libraryfile:
        for line in libraryfile:
            res = LIBRARY_RE.search(line)
            if res:
                library_dirs.append(res.group('path'))
    return library_dirs


def find_protons(library_dirs):
    """ Finds the proton directories given a list of library directories
    """
    dirs = []
    for directory in library_dirs:
        preglob_proton = os.path.join(directory, PROTON_PATH)
        for proton_dir in glob.glob(preglob_proton + '*'):
            dirs.append(proton_dir)
    return sorted(set(dirs))


def install_protonfixes(proton_dir):
    """ Installs protonfixes given the specified proton directory
    """
    us_file = os.path.join(proton_dir, 'user_settings.py')
    if not os.path.isfile(us_file):
        us_ex_file = os.path.join(proton_dir, 'user_settings.sample.py')
        shutil.copy(us_ex_file, us_file)

    protonfixes_installed = False
    with open(us_file, 'r') as user_settings:
        for line in user_settings:
            if line.startswith("import protonfixes"):
                print("Protonfixes already installed in {}, skipping".format(proton_dir))
                protonfixes_installed = True
    if not protonfixes_installed:
        print("Installing protonfixes in {}".format(proton_dir))
        with open(us_file, 'a') as user_settings:
            user_settings.write("\nimport protonfixes")


def main():
    """ Main function
    """
    try:
        steam_dir = find_steam_installation()
        library_dirs = [steam_dir, ] + find_libraries(steam_dir)
        proton_dirs = find_protons(library_dirs)
        for pdir in proton_dirs:
            try:
                install_protonfixes(pdir)
            except IOError:
                print("Protonfixes installation failed in {}, skipping".format(pdir))
    except NotADirectoryError:
        print("Could not find steam installation directory")


if __name__ == "__main__":
    main()
